# Generated by Django 4.0.2 on 2022-02-10 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_newspiece_news_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='pub_date',
        ),
    ]
