# Generated by Django 4.0.2 on 2022-02-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_comment_admitted_news_admitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='admitted',
            field=models.BooleanField(default=False, verbose_name='Допущено'),
        ),
    ]
